import { Product } from './types';

export const products: Product[] = [
  // Sofas (10 products)
  {
    id: '1',
    name: 'Scandinavian Fabric Sofa',
    price: 1299,
    store: 'Article',
    category: 'Sofa',
    style: 'Scandinavian',
    color: 'Gray',
    material: 'Fabric',
    rating: 4.7,
    reviewCount: 342,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Fabric', 'Gray']
  },
  {
    id: '2',
    name: 'Modern Velvet Sectional Sofa',
    price: 2199,
    store: 'West Elm',
    category: 'Sofa',
    style: 'Modern',
    color: 'Blue',
    material: 'Velvet',
    rating: 4.8,
    reviewCount: 567,
    imageUrl: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Velvet', 'Blue']
  },
  {
    id: '3',
    name: 'Mid-Century Leather Sofa',
    price: 1899,
    store: 'Article',
    category: 'Sofa',
    style: 'Mid-Century',
    color: 'Brown',
    material: 'Leather',
    rating: 4.6,
    reviewCount: 289,
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Leather', 'Brown']
  },
  {
    id: '4',
    name: 'Industrial Linen Loveseat',
    price: 899,
    store: 'IKEA',
    category: 'Sofa',
    style: 'Industrial',
    color: 'Beige',
    material: 'Fabric',
    rating: 4.3,
    reviewCount: 178,
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Fabric', 'Beige']
  },
  {
    id: '5',
    name: 'Contemporary Fabric Sleeper Sofa',
    price: 1599,
    store: 'Wayfair',
    category: 'Sofa',
    style: 'Modern',
    color: 'Gray',
    material: 'Fabric',
    rating: 4.5,
    reviewCount: 423,
    imageUrl: 'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Fabric', 'Gray']
  },
  {
    id: '6',
    name: 'Rustic Leather Chesterfield Sofa',
    price: 2499,
    store: 'Pottery Barn',
    category: 'Sofa',
    style: 'Rustic',
    color: 'Brown',
    material: 'Leather',
    rating: 4.9,
    reviewCount: 612,
    imageUrl: 'https://images.unsplash.com/photo-1550254478-ead40cc54513?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Leather', 'Brown']
  },
  {
    id: '7',
    name: 'Minimalist White Fabric Sofa',
    price: 1099,
    store: 'IKEA',
    category: 'Sofa',
    style: 'Scandinavian',
    color: 'White',
    material: 'Fabric',
    rating: 4.4,
    reviewCount: 256,
    imageUrl: 'https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Fabric', 'White']
  },
  {
    id: '8',
    name: 'Modern Velvet Loveseat',
    price: 1399,
    store: 'West Elm',
    category: 'Sofa',
    style: 'Modern',
    color: 'Blue',
    material: 'Velvet',
    rating: 4.7,
    reviewCount: 334,
    imageUrl: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Velvet', 'Blue']
  },
  {
    id: '9',
    name: 'Industrial Metal Frame Sofa',
    price: 1799,
    store: 'Article',
    category: 'Sofa',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.6,
    reviewCount: 201,
    imageUrl: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '10',
    name: 'Mid-Century Velvet Sofa',
    price: 1699,
    store: 'Wayfair',
    category: 'Sofa',
    style: 'Mid-Century',
    color: 'Beige',
    material: 'Velvet',
    rating: 4.5,
    reviewCount: 289,
    imageUrl: 'https://images.unsplash.com/photo-1558211583-03ed8a0b2b37?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Velvet', 'Beige']
  },

  // Chairs (10 products)
  {
    id: '11',
    name: 'Eames-Style Lounge Chair',
    price: 899,
    store: 'Article',
    category: 'Chair',
    style: 'Mid-Century',
    color: 'Black',
    material: 'Leather',
    rating: 4.8,
    reviewCount: 478,
    imageUrl: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Leather', 'Black']
  },
  {
    id: '12',
    name: 'Scandinavian Dining Chair Set',
    price: 599,
    store: 'IKEA',
    category: 'Chair',
    style: 'Scandinavian',
    color: 'White',
    material: 'Wood',
    rating: 4.5,
    reviewCount: 523,
    imageUrl: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'White']
  },
  {
    id: '13',
    name: 'Modern Velvet Accent Chair',
    price: 449,
    store: 'West Elm',
    category: 'Chair',
    style: 'Modern',
    color: 'Blue',
    material: 'Velvet',
    rating: 4.6,
    reviewCount: 312,
    imageUrl: 'https://images.unsplash.com/photo-1586158291800-2665f07bba79?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Velvet', 'Blue']
  },
  {
    id: '14',
    name: 'Industrial Metal Bar Stool',
    price: 279,
    store: 'Wayfair',
    category: 'Chair',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.4,
    reviewCount: 267,
    imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '15',
    name: 'Rustic Wooden Rocking Chair',
    price: 549,
    store: 'Pottery Barn',
    category: 'Chair',
    style: 'Rustic',
    color: 'Brown',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 189,
    imageUrl: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Wood', 'Brown']
  },
  {
    id: '16',
    name: 'Modern Fabric Office Chair',
    price: 399,
    store: 'IKEA',
    category: 'Chair',
    style: 'Modern',
    color: 'Gray',
    material: 'Fabric',
    rating: 4.3,
    reviewCount: 445,
    imageUrl: 'https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Fabric', 'Gray']
  },
  {
    id: '17',
    name: 'Mid-Century Armchair',
    price: 699,
    store: 'Article',
    category: 'Chair',
    style: 'Mid-Century',
    color: 'Beige',
    material: 'Fabric',
    rating: 4.6,
    reviewCount: 298,
    imageUrl: 'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Fabric', 'Beige']
  },
  {
    id: '18',
    name: 'Scandinavian Leather Lounge Chair',
    price: 1299,
    store: 'West Elm',
    category: 'Chair',
    style: 'Scandinavian',
    color: 'Brown',
    material: 'Leather',
    rating: 4.8,
    reviewCount: 367,
    imageUrl: 'https://images.unsplash.com/photo-1567016546203-e73936294df9?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Leather', 'Brown']
  },
  {
    id: '19',
    name: 'Industrial Wire Dining Chair',
    price: 199,
    store: 'Wayfair',
    category: 'Chair',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.2,
    reviewCount: 156,
    imageUrl: 'https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '20',
    name: 'Modern Velvet Swivel Chair',
    price: 799,
    store: 'Pottery Barn',
    category: 'Chair',
    style: 'Modern',
    color: 'Gray',
    material: 'Velvet',
    rating: 4.7,
    reviewCount: 423,
    imageUrl: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Velvet', 'Gray']
  },

  // Tables (10 products)
  {
    id: '21',
    name: 'Mid-Century Walnut Coffee Table',
    price: 649,
    store: 'Article',
    category: 'Table',
    style: 'Mid-Century',
    color: 'Brown',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 389,
    imageUrl: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Wood', 'Brown']
  },
  {
    id: '22',
    name: 'Scandinavian Oak Dining Table',
    price: 1099,
    store: 'IKEA',
    category: 'Table',
    style: 'Scandinavian',
    color: 'Beige',
    material: 'Wood',
    rating: 4.6,
    reviewCount: 512,
    imageUrl: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'Beige']
  },
  {
    id: '23',
    name: 'Industrial Metal Console Table',
    price: 449,
    store: 'Wayfair',
    category: 'Table',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.5,
    reviewCount: 278,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '24',
    name: 'Modern Glass Coffee Table',
    price: 799,
    store: 'West Elm',
    category: 'Table',
    style: 'Modern',
    color: 'White',
    material: 'Metal',
    rating: 4.4,
    reviewCount: 234,
    imageUrl: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Metal', 'White']
  },
  {
    id: '25',
    name: 'Rustic Farmhouse Dining Table',
    price: 1399,
    store: 'Pottery Barn',
    category: 'Table',
    style: 'Rustic',
    color: 'Brown',
    material: 'Wood',
    rating: 4.8,
    reviewCount: 567,
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Wood', 'Brown']
  },
  {
    id: '26',
    name: 'Scandinavian White Side Table',
    price: 299,
    store: 'IKEA',
    category: 'Table',
    style: 'Scandinavian',
    color: 'White',
    material: 'Wood',
    rating: 4.5,
    reviewCount: 412,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'White']
  },
  {
    id: '27',
    name: 'Mid-Century Marble Top Table',
    price: 1599,
    store: 'Article',
    category: 'Table',
    style: 'Mid-Century',
    color: 'White',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 298,
    imageUrl: 'https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Wood', 'White']
  },
  {
    id: '28',
    name: 'Industrial Pipe Leg Coffee Table',
    price: 549,
    store: 'Wayfair',
    category: 'Table',
    style: 'Industrial',
    color: 'Brown',
    material: 'Metal',
    rating: 4.3,
    reviewCount: 189,
    imageUrl: 'https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Brown']
  },
  {
    id: '29',
    name: 'Modern Extendable Dining Table',
    price: 1299,
    store: 'West Elm',
    category: 'Table',
    style: 'Modern',
    color: 'Gray',
    material: 'Wood',
    rating: 4.6,
    reviewCount: 445,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Wood', 'Gray']
  },
  {
    id: '30',
    name: 'Rustic Live Edge Coffee Table',
    price: 899,
    store: 'Pottery Barn',
    category: 'Table',
    style: 'Rustic',
    color: 'Brown',
    material: 'Wood',
    rating: 4.9,
    reviewCount: 623,
    imageUrl: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Wood', 'Brown']
  },

  // Desks (10 products)
  {
    id: '31',
    name: 'Modern Standing Desk',
    price: 799,
    store: 'IKEA',
    category: 'Desk',
    style: 'Modern',
    color: 'White',
    material: 'Wood',
    rating: 4.6,
    reviewCount: 534,
    imageUrl: 'https://images.unsplash.com/photo-1595514535116-988f0b05c103?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Wood', 'White']
  },
  {
    id: '32',
    name: 'Mid-Century Writing Desk',
    price: 649,
    store: 'Article',
    category: 'Desk',
    style: 'Mid-Century',
    color: 'Brown',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 389,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Wood', 'Brown']
  },
  {
    id: '33',
    name: 'Industrial Metal L-Shaped Desk',
    price: 899,
    store: 'Wayfair',
    category: 'Desk',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.5,
    reviewCount: 412,
    imageUrl: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '34',
    name: 'Scandinavian Minimalist Desk',
    price: 549,
    store: 'IKEA',
    category: 'Desk',
    style: 'Scandinavian',
    color: 'White',
    material: 'Wood',
    rating: 4.4,
    reviewCount: 367,
    imageUrl: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'White']
  },
  {
    id: '35',
    name: 'Modern Glass Computer Desk',
    price: 699,
    store: 'West Elm',
    category: 'Desk',
    style: 'Modern',
    color: 'Gray',
    material: 'Metal',
    rating: 4.3,
    reviewCount: 298,
    imageUrl: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Metal', 'Gray']
  },
  {
    id: '36',
    name: 'Rustic Wooden Executive Desk',
    price: 1299,
    store: 'Pottery Barn',
    category: 'Desk',
    style: 'Rustic',
    color: 'Brown',
    material: 'Wood',
    rating: 4.8,
    reviewCount: 489,
    imageUrl: 'https://images.unsplash.com/photo-1595428773370-77e2c24cdf37?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Wood', 'Brown']
  },
  {
    id: '37',
    name: 'Mid-Century Corner Desk',
    price: 849,
    store: 'Article',
    category: 'Desk',
    style: 'Mid-Century',
    color: 'Beige',
    material: 'Wood',
    rating: 4.6,
    reviewCount: 345,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Wood', 'Beige']
  },
  {
    id: '38',
    name: 'Industrial Pipe Frame Desk',
    price: 599,
    store: 'Wayfair',
    category: 'Desk',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.4,
    reviewCount: 267,
    imageUrl: 'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '39',
    name: 'Modern Compact Home Office Desk',
    price: 449,
    store: 'IKEA',
    category: 'Desk',
    style: 'Modern',
    color: 'White',
    material: 'Wood',
    rating: 4.5,
    reviewCount: 523,
    imageUrl: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Wood', 'White']
  },
  {
    id: '40',
    name: 'Scandinavian Oak Study Desk',
    price: 749,
    store: 'West Elm',
    category: 'Desk',
    style: 'Scandinavian',
    color: 'Beige',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 401,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'Beige']
  },

  // Beds (10 products)
  {
    id: '41',
    name: 'Modern Platform Bed Frame',
    price: 1299,
    store: 'West Elm',
    category: 'Bed',
    style: 'Modern',
    color: 'Gray',
    material: 'Fabric',
    rating: 4.7,
    reviewCount: 612,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Fabric', 'Gray']
  },
  {
    id: '42',
    name: 'Mid-Century Upholstered Bed',
    price: 1599,
    store: 'Article',
    category: 'Bed',
    style: 'Mid-Century',
    color: 'Beige',
    material: 'Fabric',
    rating: 4.8,
    reviewCount: 534,
    imageUrl: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Fabric', 'Beige']
  },
  {
    id: '43',
    name: 'Scandinavian Wooden Bed Frame',
    price: 899,
    store: 'IKEA',
    category: 'Bed',
    style: 'Scandinavian',
    color: 'White',
    material: 'Wood',
    rating: 4.5,
    reviewCount: 478,
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'White']
  },
  {
    id: '44',
    name: 'Industrial Metal Bed Frame',
    price: 749,
    store: 'Wayfair',
    category: 'Bed',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.4,
    reviewCount: 389,
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '45',
    name: 'Rustic Wooden Sleigh Bed',
    price: 1799,
    store: 'Pottery Barn',
    category: 'Bed',
    style: 'Rustic',
    color: 'Brown',
    material: 'Wood',
    rating: 4.9,
    reviewCount: 701,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
    productUrl: '#',
    tags: ['Rustic', 'Wood', 'Brown']
  },
  {
    id: '46',
    name: 'Modern Velvet Tufted Bed',
    price: 1999,
    store: 'West Elm',
    category: 'Bed',
    style: 'Modern',
    color: 'Blue',
    material: 'Velvet',
    rating: 4.8,
    reviewCount: 589,
    imageUrl: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Velvet', 'Blue']
  },
  {
    id: '47',
    name: 'Scandinavian Low Profile Bed',
    price: 1099,
    store: 'Article',
    category: 'Bed',
    style: 'Scandinavian',
    color: 'Beige',
    material: 'Wood',
    rating: 4.6,
    reviewCount: 445,
    imageUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&q=80',
    productUrl: '#',
    tags: ['Scandinavian', 'Wood', 'Beige']
  },
  {
    id: '48',
    name: 'Mid-Century Walnut Bed Frame',
    price: 1399,
    store: 'West Elm',
    category: 'Bed',
    style: 'Mid-Century',
    color: 'Brown',
    material: 'Wood',
    rating: 4.7,
    reviewCount: 512,
    imageUrl: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80',
    productUrl: '#',
    tags: ['Mid-Century', 'Wood', 'Brown']
  },
  {
    id: '49',
    name: 'Industrial Loft Bed with Storage',
    price: 1199,
    store: 'IKEA',
    category: 'Bed',
    style: 'Industrial',
    color: 'Black',
    material: 'Metal',
    rating: 4.5,
    reviewCount: 367,
    imageUrl: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80',
    productUrl: '#',
    tags: ['Industrial', 'Metal', 'Black']
  },
  {
    id: '50',
    name: 'Modern Leather Upholstered Bed',
    price: 2199,
    store: 'Pottery Barn',
    category: 'Bed',
    style: 'Modern',
    color: 'White',
    material: 'Leather',
    rating: 4.8,
    reviewCount: 634,
    imageUrl: 'https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&q=80',
    productUrl: '#',
    tags: ['Modern', 'Leather', 'White']
  }
];
